"""Add promo_code column to subscribers

Revision ID: 10af0f2a9bb7
Revises: e912664370b6
Create Date: 2025-03-28 16:40:51.304505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10af0f2a9bb7'
down_revision = 'e912664370b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promo_code', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_column('promo_code')

    # ### end Alembic commands ###
