"""Add user_agent field to DeviceUsage

Revision ID: 6f9ad8d0f20d
Revises: 851f0793f381
Create Date: 2025-03-24 21:57:18.301415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9ad8d0f20d'
down_revision = '851f0793f381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_usage', schema=None) as batch_op:
        batch_op.drop_column('user_agent')

    # ### end Alembic commands ###
